### ISSUE TITLE
ipopt is not available anymore from homebrew/science 

### ISSUE THREAD

**Issue by traversaro** [robotology/homebrew-formulae#12]
Related issues:  https://github.com/RobotLocomotion/drake/issues/7679 , https://github.com/Homebrew/homebrew-science/issues/6365

In a nutshell, homebrew/science was closed, so we should find another solution for our ipopt dependency. 
The most straightforward solution is to host a copy of the last ipopt and mumps formula in this repo. 

opencv formula was also maintained in homebrew/science, but it has been migrated to homebrew/core https://github.com/Homebrew/homebrew-science/blob/master/tap_migrations.json#L54 . We should update the dependencies to point to the core version of the formula.

cc @claudiofantacci

**Comment by traversaro** [comment]
If I understand everything correctly (I don't have access to a mac at the moment) this means that the `icub-main` formula is broken.

**Comment by traversaro** [comment]
A similar issue affects the dart formula as well, see https://github.com/dartsim/homebrew-dart/blob/8a6d175ff7db915d675612c376ec5d8d89a0665a/Formula/dartsim6.rb#L31 . 
cc @jslee02

**Comment by jslee02** [comment]
@traversaro Thanks for the heads-up.

I'm submitting series of PRs for migrating `ipopt` and its dependencies to `homebrew-core`:
* [parmetis](https://github.com/Homebrew/homebrew-core/pull/22361)
* [scotch](https://github.com/Homebrew/homebrew-core/pull/22362)
* scotch5
* ipopt

**Comment by traversaro** [comment]
That's great @jslee02 ! Thanks and happy new year!

**Comment by claudiofantacci** [comment]
Hi everyone! I also noticed just now with a `brew update` about homebrew-science deprecation.
It was already started some times ago and some formulae have been ported in the meantime, lik for example `opencv`.

@jslee02 thanks for your effort, really appreciated! 🏆 🎉 

As a result of the deprecation `icub-main --with-ipopt` is broken, unless `ipopt` was already installed with brew before deprecation.
IMHO, we can wait for @jslee02 work and then test and update the formulae at that time.
I'll keep an eye on this.

**Comment by traversaro** [comment]
cc @DanielePucci

**Comment by jslee02** [comment]
It seems being accepted formulae by homebrew-core takes time. As a temporary solution, I [hosted](https://github.com/dartsim/homebrew-dart/pull/49) `ipopt` and its dependencies in https://github.com/dartsim/homebrew-dart, and it seems to work with DART (on my macbook). I might continue to work on moving those formulae to homebrew-core eventually.

In the meantime, I think you guys could use them from https://github.com/dartsim/homebrew-dart or host them here at your convenience.

**Comment by traversaro** [comment]
@claudiofantacci I would go for using `dartsim/dart/ipopt` as soon as https://github.com/dartsim/homebrew-dart/pull/49 is merged, so we have a single trusted point in which to fix issues or problems. 

Thanks a lot @jslee02 .

**Comment by claudiofantacci** [comment]
Reasonable to me, and thanks @jslee02 for the effort and your help! Appreciated 🙇 

We can go for `dartsim/dart/ipopt` and join strenght to make it a strong and reliable formula 💪 
Hopefully we will make it for `homebrew-core` in resonable time!

**Comment by traversaro** [comment]
cc @nunoguedelha

**Comment by traversaro** [comment]
cc @lucaTagliapietra

**Comment by adam-erickson** [comment]
Again, if anyone runs into this issue, IpOpt can be installed via Homebrew with this temporary solution until it is accepted in homebrew-core:

`brew install dartsim/dart/ipopt`

**Comment by yujund** [comment]
Many thanks!

**Comment by traversaro** [comment]
As pointed  out in https://github.com/dartsim/homebrew-dart/issues/76#issuecomment-500458878, a ipopt formula is now available in homebrew core. If it works correctly, I think we can definitely close this issue. : )

**Comment by traversaro** [comment]
As discussed in https://github.com/dartsim/homebrew-dart/issues/76#issuecomment-500458878 , an ipopt formula was made available in the core homebrew repo in https://github.com/Homebrew/homebrew-core/pull/38270 . For this reason, I think  we can finally close this issue.
