### ISSUE TITLE
Update RTF formula to v1.4.0

### ISSUE THREAD

**Issue by aerydna** [robotology/homebrew-formulae#14]
RTF v1.4.0 was released, please update the formula.

**Comment by claudiofantacci** [comment]
Should we update to V2.0.0 or v1.4.0?

Consider the chain of dependency of the formulae. Latest `icub-main` (v.1.12.0) requires `YARP` v3.1.0.

Maybe we have to hold back the version for a while.

**Comment by drdanz** [comment]
I'd say 2.0.0, and rename to robot-testing-framework

**Comment by claudiofantacci** [comment]
Ok, but then our `YARP` formula needs to be updated with the latest version and this, in turn, will not allow us to install icub-main from brew because the latest stable requires `YARP` 3.1.0.

**Comment by drdanz** [comment]
Formula was removed in #29
