### ISSUE TITLE
Update YARP formula to v3.4.2

### ISSUE THREAD

**Issue by mbrunettini** [robotology/homebrew-formulae#16]

**Comment by GengTianyu** [comment]
Hello, I have installed yarp by Homebrew and tried to update my yarp to v3.3.2, while failed.
The result show "robotology/formulae/yarp 2.3.70.2 already installed", so please tell me how to update it, think you very much

**Comment by traversaro** [comment]
Hi @GengTianyu , at the moment the homebrew formula contained in this repo are not really mantained, so I suggest you to compile YARP from source, or use the https://github.com/robotology/robotology-superbuild to install YARP and its dependencies.

**Comment by drdanz** [comment]
Formula was removed in #29
