### ISSUE TITLE
Remove unmantained formulas? 

### ISSUE THREAD

**Issue by traversaro** [robotology/homebrew-formulae#26]
A lot of homebrew formulas contained in this repo are currently unmaintained, and some of them are completely unusable (see https://github.com/robotology/homebrew-formulae/issues/25). They are just a source of confusion for users. 

Unless we are able to find some forces to mantain these formulas, I propose to remove the following unmantained formulas: 
* `yarp` 
* `gazebo-yarp-plugins` 
* `icub-main` 
* `robot-testing`

**Comment by traversaro** [comment]
cc @vtikha @drdanz @pattacini @mbrunettini

**Comment by drdanz** [comment]
We have a mac for testing available if anyone wants to work on them

**Comment by drdanz** [comment]
Formulas were removed in #29
