### ISSUE TITLE
Add ycm formula

### ISSUE THREAD

**Issue by traversaro** [robotology/homebrew-formulae#6]
ycm (https://github.com/robotology/ycm) is used for several robotlogy superbuild and projects. 
It is typically bootstrapped by the superbuilds, but this approach has some problems (see for example [1]). It would be convenient if we had an homebrew formula for ycm so macOs user could grab ycm directly from homebrew, avoiding the need for bootstrapping.

[1] https://github.com/robotology/ycm/issues/105

**Comment by francesco-romano** [comment]
done in 352aed07412fab13cead633bc6c9aa0a9d4e972c
