### ISSUE TITLE
This repo’s name is icorrect and confusing

### ISSUE THREAD

**Issue by vitorgalvao** [robotology/homebrew-formulae#7]
I found this repo because I had a confused user (I’m a Hombrew-Cask maintainer). Casks and Formulae are different things, just as Homebrew and Homebrew-Cask are different. They are similar and have similar goals, but have important differences and (slightly) different ways of being installed.

This repo doesn’t have any casks, it has formulae, and as such the `homebrew-cask` name is confusing.

**Comment by claudiofantacci** [comment]
Hi @vitorgalvao , thanks for reaching out!

Thanks for your comments and suggestions.
We are super open to discussions and improvements 😄 

I guess the confusion between formula and cask are caused by the fact that after building YARP you will get both CL executables and macOS apps.
Maybe we could rename the repo as `homebrew-formulae`.

@francesco-romano and @drdanz will be able to provide you a much more precise answer.

**Comment by vitorgalvao** [comment]
@claudiofantacci I understand your logic, but casks and formulae are different internally (how the ruby file is structured) and externally (how you interact with it, using `brew cask` or just `brew`). So they are defined by what they *are*, not what they *install*.

Even I was confused when I saw `cask` in the `tap` command and `brew install` (instead of `brew cask install`) in the installation command.

**Comment by claudiofantacci** [comment]
@vitorgalvao that's totally fine and understandable as well 😄
There will be no problem for reaching a solution that will accommodate all needs and, in particular, your observations.

We are always keen to improvements and your suggestions are super-welcome for us!
There has been a mistake, but we did not want to cause any trouble/confusion to anyone... 😮!
As soon as @francesco-romano and @drdanz will reach us here we will do the proper changes 👍 

Would `homebrew-formulae` be clearer?

**Comment by vitorgalvao** [comment]
> Would `homebrew-formulae` be clearer?

Definitely. But anything else will be clearer, really. `cask` is the one word that causes confusion because it muddles the meaning (to something else that exists but isn’t what the repo contains).

**Comment by claudiofantacci** [comment]
Ok ok 😕 ...
[I see that this caused troubles to you, but mistakes can happen.](https://github.com/caskroom/homebrew-cask/issues/32840)

**Comment by vitorgalvao** [comment]
@claudiofantacci To be clear, I’m not mad or trying to be rude in the slightest. That is not my right, and far from me to ever think to lash out at you. You have been nothing but courteous.

If there was something you perceived as wrong in my tone, I apologise. I only aimed to be clear  about the matter, not insulting or disrespectful.

**Comment by claudiofantacci** [comment]
That's ok @vitorgalvao , no worries at all and thanks for your last message 😄

**Comment by claudiofantacci** [comment]
We have planned to change the name of the repository in the near future 😄 
We linked this issue to a dedicated [Milestone](https://github.com/robotology/homebrew-cask/milestone/3) where more details are provided.

**Comment by francesco-romano** [comment]
We schedule the renaming for tomorrow as YARP will have a new release

@claudiofantacci @drdanz

**Comment by francesco-romano** [comment]
Done
