### ISSUE TITLE
YARP formula failing on Travis

### ISSUE THREAD

**Issue by traversaro** [robotology/homebrew-formulae#9]
In several macOS-based Travis builds we are experiencing the following failure of the yarp formula: 
~~~
==> Installing robotology/formulae/yarp
==> Downloading https://github.com/robotology/yarp/archive/v2.3.70.1.tar.gz
==> Downloading from https://codeload.github.com/robotology/yarp/tar.gz/v2.3.70.
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
Last 15 lines from /Users/travis/Library/Logs/Homebrew/yarp/01.cmake:
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
CMake Error in src/yarpmotorgui/CMakeLists.txt:
  Cannot find source file:
main.cpp;flowlayout.cpp;jointitem.cpp;mainwindow.cpp;partitem.cpp;piddlg.cpp;sequencewindow.cpp;sliderOptions.cpp;sliderWithTarget.cpp;startdlg.cpp;flowlayout.h;jointitem.h;log.h;mainwindow.h;partitem.h;piddlg.h;sliderOptions.h;sliderWithTarget.h;yarpmotorgui.h;sequencewindow.h;startdlg.h;res.qrc;/tmp/yarp-20171122-14172-1efr2r7/yarp-2.3.70.1/src/yarpmotorgui/qrc_res.cpp;jointitem.ui;mainwindow.ui;piddlg.ui;sequencewindow.ui;startdlg.ui;sliderOptions.ui;/tmp/yarp-20171122-14172-1efr2r7/yarp-2.3.70.1/src/yarpmotorgui/ui_jointitem.h;/tmp/yarp-20171122-14172-1efr2r7/yarp-2.3.70.1/src/yarpmotorgui/ui_mainwindow.h;/tmp/yarp-20171122-14172-1efr2r7/yarp-2.3.70.1/src/yarpmotorgui/ui_piddlg.h;/tmp/yarp-20171122-14172-1efr2r7/yarp-2.3.70.1/src/yarpmotorgui/ui_sequencewindow.h;/tmp/yarp-20171122-14172-1efr2r7/yarp-2.3.70.1/src/yarpmotorgui/ui_startdlg.h;/tmp/yarp-20171122-14172-1efr2r7/yarp-2.3.70.1/src/yarpmotorgui/ui_sliderOptions.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

-- Generating done
-- Build files have been written to: /tmp/yarp-20171122-14172-1efr2r7/yarp-2.3.70.1
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/robotology/homebrew-formulae/issues
~~~

**Comment by claudiofantacci** [comment]
@traversaro could you please provide a link to a failed Travis build?
I rapidly checked some random PR but could not find one with a failed macOS build.

The error is pretty strange to me. Basically the build is not able to find **all** the files related to `yarpmotorgui`, which is weird because an error like that should be present in all the builds enabling GUIs right?

Anyway, let's see this in detail.

**Comment by traversaro** [comment]
https://travis-ci.org/robotology/codyco-superbuild/jobs/305608313

**Comment by traversaro** [comment]
https://travis-ci.org/robotology/idyntree/jobs/305607355

**Comment by claudiofantacci** [comment]
I fear that something is going wrong with `brew`. On `codyco` the build failed because of a failed `brew update`, while for `idyntree` I actually find the above-reported error, which is weird.

Do you mind restarting the two Travis jobs and see what happen? Or have you already did it?

**Comment by traversaro** [comment]
Yep, I restarted several jobs and this is still happening:
* https://travis-ci.org/robotology/codyco-superbuild
* https://travis-ci.org/robotology/idyntree

cc @DanielePucci

**Comment by francesco-romano** [comment]
It is not a travis fault.
Something has changed somewhere (probably cmake).
I am not able to compile yarp from a clean build even without brew

**Comment by claudiofantacci** [comment]
@francesco-romano what kind of `CMake` version do you have?

I, instead, have problem with `brew`. I can't use my own formulae anymore. It gives me error while performing `brew update`, which wasn't happening before.

**Comment by francesco-romano** [comment]
Just updated brew without any problem.

My CMake is `3.10.0`.
Note that they have changed some behaviour on the `AUTOMOC`
>  When using "AUTOMOC" or "AUTOUIC", source files that are
 "GENERATED" will be processed as well. They were ignored by
 "AUTOMOC" and "AUTOUIC" in earlier releases. See policy "CMP0071".

I don't know if this broke something (as we are having problem in the Qt guis)

**Comment by traversaro** [comment]
With the last cmake (3.10.0) and macOS Sierra 10.12.5 (16F73) I have no problem in compiling YARP `master` without brew (or even with brew). `devel` instead fails with the homebrew error! Opening an issue in YARP.

**Comment by francesco-romano** [comment]
The strange thing is that it happens also on the 2.3.70.1 release (which was working)

**Comment by traversaro** [comment]
See https://github.com/robotology/yarp/issues/1464 .

**Comment by claudiofantacci** [comment]
I have `cmake` 3.9.4 (3.9.4_1 from bottle), macOS Sierra 10.12.6, and I don't have any problem compiling `yarp` on `devel` and `master` branch.

**Comment by traversaro** [comment]
Apparently there is the same problem also on master, and it only worked the first time.

**Comment by claudiofantacci** [comment]
I guess than that it's because of the new policy [CMP0071](https://cmake.org/cmake/help/v3.10/policy/CMP0071.html).

**Comment by claudiofantacci** [comment]
BTW `brew` has updated now and the error on third-party taps has now disappeared.

**Comment by francesco-romano** [comment]
After https://github.com/robotology/yarp/issues/1464, remember to update the formula, otherwise people will not be able to use this.

**Comment by jeljaik** [comment]
I'm having the same problem when issuing `brew install robotology/formulae/yarp` on macOS High Sierra 10.13.1. and CMake 3.10.0.

**Comment by jeljaik** [comment]
With `brew install robotology/formulae/yarp --HEAD` I get: 

```
CMake Error at cmake/YarpFindDependencies.cmake:162 (message):
  Optional package RTF not found.  Please install it or disable the option
  "YARP_COMPILE_RTF_ADDONS" to build yarp.
Call Stack (most recent call first):
  cmake/YarpFindDependencies.cmake:532 (check_optional_dependency)
  CMakeLists.txt:71 (include)
```

**Comment by traversaro** [comment]
This is causing also a Travis failure on the codyco-superbuild builds: https://travis-ci.org/robotology/codyco-superbuild/jobs/311660897 .

**Comment by claudiofantacci** [comment]
Don't we have two different problems here?

Problem 1:
> I'm having the same problem when issuing brew install robotology/formulae/yarp on macOS High Sierra 10.13.1. and CMake 3.10.0. What was the way to proceed at this point?

Was fixed with this PR https://github.com/robotology/yarp/pull/1465 and with a new YARP release we will be able to fix the formula.

Problem 2:



> With brew install robotology/formulae/yarp --HEAD I get:
> 
> CMake Error at cmake/YarpFindDependencies.cmake:162 (message):
>   Optional package RTF not found.  Please install it or disable the option
>   "YARP_COMPILE_RTF_ADDONS" to build yarp.
> Call Stack (most recent call first):
>   cmake/YarpFindDependencies.cmake:532 (check_optional_dependency)
>   CMakeLists.txt:71 (include)

This may be a configuration option that needs further investigations.

**Comment by traversaro** [comment]
Problem 2: this is due to the fact that YARP devel depends on RTF devel, not on RTF master.

**Comment by claudiofantacci** [comment]
> Problem 2: this is due to the fact that YARP devel depends on RTF devel, not on RTF master.

Hey! Copying my reply? I got you some second before 😛  J/K!

Anyway, that's the problem. Maybe with the next minor release of YARP + RTF everything will be fixed.
